### ISSUE TITLE
More document about download packages

### ISSUE THREAD

**Issue by ShuiRuTian** [microsoft/BuildXL#1328]
Here is a good document about how to download packages for JS repo: https://github.com/microsoft/BuildXL/blob/021cb639620d39ffc3a7d5cb784f877f2ed8c7aa/Documentation/Wiki/Frontends/js-package-install.md

However, it's kind of useless, because I do not know how to use it!

And it seems the document is internally: please refer `Configuring a 'prep' build to do package install` section in https://eng.ms/docs/cloud-ai-platform/devdiv/one-engineering-system-1es/1es-build/buildxl/buildxl-in-cloudbuild#javascript-on-buildxl-in-cloudbuild

Add some document or link would be helpful.

**Comment by smera** [comment]
Hi @ShuiRuTian ,
The internal document is CloudBuild-specific, which is not a system available outside of MS, that's why we don't have a reference on GitHub about this (or more generally, any CloudBuild reference on GitHub).
These documents are referring to making package install happen as a BuildXL build, which is particularly useful on CloudBuild. Outside of CB, this is probably not very relevant and doing package install outside of BuildXL is probably the easiest (e.g. as a step in your YAML pipeline, for the case of an ADO build).
