### ISSUE TITLE
MSBuild - Pip Dependencies

### ISSUE THREAD

**Issue by Zo11** [microsoft/BuildXL#1337]
Hello, I'm trying to build a Visual Studio solution using BuildXL and when I run the build I get:
```
Missing dependency between a reader and a writer. Please declare a dependency between these pips if you believe the access is legitimate
```
How do I specify this dependency? I am struggling to find documentation on how to do it. 

Can someone point me in the right direction?

***
Edit to give more context:

I'm trying to build a solution of third party libraries and then my own solution at the same time using this:

```
    resolvers: [
        {
            kind: "MsBuild",
            root: d`ThirdParty`,
            fileNameEntryPoints: [
                r`ThirdParty.sln`,
            ],
            moduleName: "ThirdParty",
            msBuildSearchLocations: [d`C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin`],
            useLegacyProjectIsolation: true
        },
        {
            kind: "MsBuild",
            root: d`.`,
            fileNameEntryPoints: [
                r`MySolution.sln`,
            ],
            moduleName: "MySolution",
            msBuildSearchLocations: [d`C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin`],
            useLegacyProjectIsolation: true
        }
    ],
```
When one of the projects in MySolution touches one of the files generated by ThirdParty.sln, I get that error message. 

Thanks!

**Comment by smera** [comment]
Hello,
The missing dependency error is expected since each resolver will produce a build graph, but the final graph will be just the two graphs side by side, without any edge between them. BuildXL needs project-to-project dependencies completely specified, which means that if there are cross-resolver dependencies, they need to be declared. We don't support this ability yet for the MSBuild resolver (we do for other resolvers), I'll add this to our backlog. One possible path forward is to build one solution file that can include all your projects, so you can define your build with just one resolver.

Thanks,
Serge.
