### ISSUE TITLE
MSBuild - Set Non Scrubbable Paths

### ISSUE THREAD

**Issue by Zo11** [microsoft/BuildXL#1338]
Hello,

On a related note to issue https://github.com/microsoft/BuildXL/issues/1337:

I'm trying to run the build in two steps, first build the third party libraries, then build my solution.

The third party libraries build fine by themselves, but while building MySolution.sln, all the third party libraries are deleted (scrubbed). I can see in the logs `verbose DX0858: Scrubber deletes file ...` for every single third party .lib.

The third party folder lives inside the main solution:
```
root/
 ├── config.dsc
 ├── MySolution.sln
 └── ThirdParty/
     └── ThirdParty.sln
```
How can I tell BuildXL not to delete all the .lib files inside ThirdParty?

As with issue 1337, I've been navigating the code and documentation trying to find the answer but no luck so far.

I see that the Engine uses a set of paths as nonScrubbable, as well as the nonScrubbable paths of the FrontEnd controller: `FrontEndController.GetNonScrubbablePaths()`, which appear to be the root of the front end, but I don't know if I should be going down this path.

Thanks in advance for any help.

**Comment by smera** [comment]
Hello,
BuildXL tries to deliver build determinism by making sure stale outputs (produced in older builds) do not interfere with the currently running build. Outputs are then flagged when produced and 'scrubbed' on the next build. 
My recommendation would be to merge both steps into the same build. Besides the scrubbing issue, you are more likely to get better parallelism in this way since BuildXL will be able to schedule your projects based on the 'big picture', as opposed to imposing artificial chokepoints due to partitioning the build process in stages.
If that's not an easy option, you can pass `/unsafe_SkipFlaggingSharedOpaqueOutputs`. This will disable the scrubbing behavior in between builds. Caveat: determinism can be affected (e.g. you build once, outputs are left on disk and are used by the next build as inputs, and therefore the result can be different). I'd also recommend that you manually remove all stale outputs (e.g. git clean- xdf) before passing this flag, since outputs are flagged when produced)

Thanks!
