### ISSUE TITLE
CMake support or example

### ISSUE THREAD

**Issue by ktf** [microsoft/BuildXL#282]
Maybe there is something I am missing, but do I understand correctly that BuildXML could injest CMakeLists.txt and accelerate the builds for the products described there? If yes, how? Is there any "hello world" example for CMake?

**Comment by jbayardo** [comment]
Yes, that is correct: there is experimental support for CMake. We have been able to build successfully many projects (llvm, pcl, vtk, among others). The caveats are:

- Current testing has focused on build support rather than install
- It may require some additional work if your project has logic that does not fit within the BuildXL model

As a starting point, I have set up an example @ https://github.com/jbayardo/example-cmake-config with intructions in the config.bc file, as usual, the first run should be slow, subsequent ones fast.

**Comment by bgianfo** [comment]
@jbayardo, is there a reason why it wasn't just added as an example in the Examples directory? It's pretty confusing that it's sitting in it's own repro.

**Comment by jbayardo** [comment]
@bgianfo, haven't had the time to properly address this in our documentation. Doing so would also require adding more information on features from the CMake and MsBuild resolvers, which is beyond the scope of my work right now.

**Comment by jbayardo** [comment]
The example for CMake has been added to https://github.com/microsoft/BuildXL/tree/master/Examples/CMakeHelloWorld

**Comment by dannyvv** [comment]
It seems this issue has been resolved. Closing the issue for now. Please let us know if this is not resolved satisfactory.
